apiVersion: v1
kind: ConfigMap
metadata:
  name: jobintel-config
  namespace: jobintel
data:
  CAREERS_MODE: "LIVE"
  AI_ENABLED: "0"
  REDACTION_ENFORCE: "1"
  JOBINTEL_PROVIDER_ERROR_RATE_MAX: "0.25"
  JOBINTEL_PROVIDER_MIN_JOBS: "1"
  JOBINTEL_PROVIDER_MIN_SNAPSHOT_RATIO: "0.2"
  JOBINTEL_PROVIDER_MAX_ATTEMPTS: "3"
  JOBINTEL_PROVIDER_BACKOFF_BASE: "0.5"
  JOBINTEL_PROVIDER_BACKOFF_MAX: "3.0"
