apiVersion: v1
kind: ConfigMap
metadata:
  name: jobintel-config
  namespace: jobintel
data:
  PUBLISH_S3: "1"
  PUBLISH_S3_DRY_RUN: "0"
  JOBINTEL_S3_PREFIX: "jobintel"
  JOBINTEL_AWS_REGION: "us-east-1"
